### ISSUE TITLE
use tdd to define a class that defines a list of pairs of real numbers

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team5#83]
this list could be used e.g., for representing a set of data points to draw in an xy graph, 
e.g., x is time and y is weight. the series is the list of data points.

- [x]  function recod(x,y)
- [x] iteration over pairs sorted by
- [x] statistics, such as count of data points.
- [x] implement linear regression https://en.wikipedia.org/wiki/Simple_linear_regression

**Comment by yossigil** [comment]
good luck

**Comment by shaked-sapir** [comment]
@dormaayan @yossigil Hi, I have a few questions:
1. "function recod(x,y)" - is this a typo of "record", i.e to add (x,y) to the list?
2. "iteration over pairs sorted by" : sorted by what? x vals, y vals, both? whatever I want? that also leads me to: 
3. Can I assume that x's values are unique? (So I can implement the list as a SortedMap with meaning to sorted keys, instead of implement it as an ArrayList or something similar)

**Comment by shaked-sapir** [comment]
reopened as part of issue #124

**Comment by shalev-kuba** [comment]
seems good,
it can be seen you've done quite job over here.
i am closing this issue.
